### PR TITLE
section_4_picture created

### PR DESCRIPTION
**Pull request by svichkarolga**
section _4_picture was created

### CODE REVIEW

**Review by OlhaKadeeva — CHANGES_REQUESTED** [review]
add hidden h2

**Review by OlhaKadeeva — CHANGES_REQUESTED** [review]
title

**Review by OlhaKadeeva — CHANGES_REQUESTED** [review]
visually-hidden

**Comment by svichkarolga** [comment]
defis was added

**Review by OlhaKadeeva — APPROVED** [review]

**Pull request merged**
